<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLR2DEVLP0630" ignored="1" name="Personal loan" tests="3" failures="1" timestamp="05 Jan 2022 07:20:44 GMT" time="0.152" errors="0">
  <testcase name="Demo" time="0.005" classname="Test1.day1"/>
  <testcase name="Demo5" time="0.002" classname="Test1.day1"/>
  <testcase name="Demo2" time="0.056" classname="Test1.day2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test1.day2.Demo2(day2.java:26)
at java.util.concurrent.FutureTask.run(FutureTask.java:277)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:785)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo2 -->
  <testcase name="Demo" time="0.0" classname="Test1.day2">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- Personal loan -->
